### ISSUE TITLE
Link to Rojo documentation in the "Welcome to Rojo" vscode screen goes to a 404

### ISSUE THREAD

**Issue by joshuaclausen** [evaera/vscode-rojo#4]
Minor "issue", I know.  But it's always nice when they're easy ones ;)

In the "Next Steps" section:

Next steps

Now that you've got the hang of using Rojo, you should take a look at the **official documentation** which dives in deeper on some more advanced features of Rojo that you'll definitely want to know about! Learn how to:

Make your script.......

The "official documentation" link currently goes to: https://lpghatguy.github.io/rojo/sync-details/

I'd suggest going to: https://lpghatguy.github.io/rojo/master/

**Comment by evaera** [comment]
Yeah he changed the URL recently. I'll have this updated in the next release
