### ISSUE TITLE
Show Rojo release notes button upon installing new version

### ISSUE THREAD

**Issue by evaera** [evaera/vscode-rojo#5]

**Comment by DianaNites** [comment]
It'd be nicer to use `CHANGELOG.md` per the [VSCode docs](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#marketplace-integration), "A CHANGELOG.md file at the root of your extension will be used as the contents for the extension's change log."

**Comment by evaera** [comment]
This issue refers to the Rojo release notes when a new version is installed, not the extension itself, but I will look into your suggestion for the extension
