### ISSUE TITLE
Typo Quick-Start Guide: Option in context menu doesn't match

### ISSUE THREAD

**Issue by DiegoAlpizar** [evaera/vscode-rojo#6]
In the 3rd step:
(...) 'Right-click on the folder you created in the last step ("Game" in our case) in the VS Code Explorer panel, and choose "Rojo: **Create partition** here...".' ...

Context meny actually reads:
"Rojo: **Sync from** here"

![MinorTypo](https://user-images.githubusercontent.com/48010731/55678965-fd1c5100-58bf-11e9-91ff-399cd1177080.png)

**Comment by evaera** [comment]
Thanks for reporting this. The guide hasn't been updated since Rojo 0.4.x, and back then the menu used to be "create partition here". Waiting for 0.5.x to come out of alpha before updating the guide for it. I'll publish a patch to fix this typo though.
